### ISSUE TITLE
support net core?

### ISSUE THREAD

**Issue by mingyangzhu** [karisigurd4/DocumentLab#2]
hi can  support net core or high net version(eg.net 5...)

**Comment by karisigurd4** [comment]
Hey! Unfortunately no support for .Net Core or .Net 5.*. The only framework target I've built on is .Net Framework 4.6.1. Hopefully some day I'll get the time to look at getting it done.

**Comment by mingyangzhu** [comment]
> Hey! Unfortunately no support for .Net Core or .Net 5.*. The only framework target I've built on is .Net Framework 4.6.1. Hopefully some day I'll get the time to look at getting it done.

Thank you for your reply, your work is great！！！
