### ISSUE TITLE
Get matching values as array

### ISSUE THREAD

**Issue by einer20** [karisigurd4/DocumentLab#3]
I have an image that repeats the same sentence multiple times like for example:

> Matricula 40339 text text text text text text
> 
> Matricula 4033 text text text text text text

I want to get all values as array.  But when i do the script
```
Identification:
Text(Matricula) Right [Number];
```

I get the first one only but Im expecting 2.
How can I do this?

**Comment by karisigurd4** [comment]
You can do

```
Identification:
Any Text(Matricula) Right [Number];
```

Hopefully works!

**Comment by einer20** [comment]
@karisigurd4 im so sorry for my late response. It worked! I could get 87% of the values that I wanted from the image.

Edit:

Omg what a lazy i am. [It was right there in the documentation](https://github.com/karisigurd4/DocumentLab/blob/master/Documentation/QueryLanguage.md#building-patterns)
